name = "your-house-pourri"
compatibility_date = "2026-04-02"

[assets]
directory = "./"

routes = [
  { pattern = "palma-pourri.org/*", custom_domain = true },
  { pattern = "www.palma-pourri.org/*", custom_domain = true }
]
